version: '3.8'

services:
  terraria-server:
    image: ghcr.io/beardedio/terraria:latest
    container_name: terraria-server
    stdin_open: true
    tty: true
    environment:
      - world=YourWorldName # use this if you already have a world save in the config directory
      # comment out the above two lines if you don't have a world and need to generate one
    networks:
      - proxy-tier
    volumes:
      - ./config:/config
    ports:
      - 7777:7777
    restart: unless-stopped

networks:
  proxy-tier:
    external: true
